spring.application.name=portfolio

spring.cloud.azure.keyvault.secret.property-sources[0].name=kv-portfolioapp-dev
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://kv-portfolioapp-dev.vault.azure.net/
spring.cloud.azure.keyvault.secret.property-sources[0].secret-keys=spring-datasource-url
spring.cloud.azure.keyvault.secret.property-sources[0].refresh-interval=0

spring.datasource.url=${spring-datasource-url}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.pool-name=portfolioHikariPool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
